/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define ADC_C1_BASE  				0x40012000UL
#define ADC_CR1_OFFSET 				0x04UL
#define ADC1_REG_ADDRESS  			(ADC_CR1_OFFSET + ADC_C1_BASE)
#define RCC_EN_ADC1_BASE 			0x40023800UL
#define RCC_EN_ADC1_OFFSET 			0x44UL
#define RCC_ADC1_ADDRESS  			(RCC_EN_ADC1_BASE + RCC_EN_ADC1_OFFSET)


int main(void)
{
	uint32_t *prcc_en_reg = (uint32_t*)RCC_ADC1_ADDRESS;
	uint32_t *pAdc_reg = (uint32_t*) ADC1_REG_ADDRESS;

	// enable the RCC clock for ADC1 CR1 reg
	*prcc_en_reg |= (1 << 8);

	// Set the Scan mode (Bit 8 of ADC1 CR1 Reg)
	*pAdc_reg |= (1 << 8);

	/* Loop forever */
	for(;;);
}
